config/routes.rb
Rails.application.routes.draw do
  resources :employees do
    post :import, on: :collection
  end
  root "home#index"
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
end

app/models/payslip.rb
class Payslip
  include ActiveModel::Model
  attr_accessor :employee, :pay_period_start_date, :pay_period_end_date
  attr_reader :calculation

  def initialize(attributes={})
    super
    @calculation = PayslipCalculator.new(
        annual_salary: @employee.annual_salary,
        super_rate: @employee.super_rate,
        pay_period_start_date: @pay_period_start_date,
        pay_period_end_date: @pay_period_end_date,
        annual_tax: TaxRange.annual_tax(@employee.annual_salary)
    ) if self.valid?
  end

  validates :employee, :pay_period_start_date, :pay_period_end_date, presence: true
  validate :dates_are_in_the_same_month?

  def name
    @employee.full_name
  end

  def pay_period
    "#{@pay_period_start_date} - #{@pay_period_end_date}"
  end

  def gross_income
    @calculation.gross_income
  end

  def income_tax
    @calculation.income_tax
  end

  def net_income
    @calculation.net_income
  end

  def super_amount
    @calculation.super_amount
  end

  private

    def dates_are_in_the_same_month?
      if @pay_period_start_date.to_date.month == @pay_period_end_date.to_date.month
        true
      else
        errors.add(:pay_period_end_date, 'must be in the same month as start date')
        false
      end
    end
end

app/controllers/concerns/payslips_controller.rb
class PayslipsController < ApplicationController
  before_action :set_form_params
  before_action :set_params, only: [:show_multiple]
  add_crumb('Payslips') {|instance| instance.send :payslips_path }

  def index
    @tax_range_empty ||= TaxRange.all.empty?
    flash.now[:error] = 'Please add employees profiles first to setup Tax Range model.'if @tax_range_empty
  end

  def show_multiple
    respond_to do |format|
      if payslip_collection
        format.js { render 'show_multiple' }
        format.csv
      else
        flash[:error] = @errors.full_messages
        format.js { render 'show_multiple_error' }
      end
    end
  end

  private

    def payslip_collection
       @payslips = []; @errors = ''
       @employees.each do |employee|
         payslip = Payslip.new(employee: employee, pay_period_start_date: @pay_period_start_date, pay_period_end_date: @pay_period_end_date )
         if payslip.errors.any?
           @errors = payslip.errors
         else
           @payslips << payslip
         end
       end
       @errors.empty?
    end

    def set_form_params
      @employees_for_select ||= Employee.all
    end

    def set_params
      @employees  = Employee.find(payslip_params[:employee_id])     if payslip_params[:employee_id]
      @pay_period_start_date = payslip_params[:payslip_start_date]  if payslip_params[:payslip_start_date]
      @pay_period_end_date   = payslip_params[:payslip_end_date]    if payslip_params[:payslip_end_date]
      @params_for_csv = {employee_id: @employees.map(&:id), payslip_end_date: @pay_period_end_date, payslip_start_date: @pay_period_start_date}
    end

    def payslip_params
      params[:payslips]
    end
end

app/controllers/payslips_controller.rb
class PayslipsController < ApplicationController

  before_action :set_form_params
  before_action :set_params,        only: [:show_multiple]

  add_crumb('Payslips') {|instance| instance.send :payslips_path }

  def index
    @tax_range_empty ||= TaxRange.all.empty?
    flash.now[:error] = 'Please run rake db:seed to setup Tax Range model. Payslip generator cannot work without valid tax ranges.'if @tax_range_empty
  end

  def show_multiple
    respond_to do |format|
      if payslip_collection
        format.js { render 'show_multiple' }
        format.csv
      else
        flash[:error] = @errors.full_messages
        format.js { render 'show_multiple_error' }
      end
    end
  end

  private

  def payslip_collection
     @payslips = []; @errors = ''
     @employees.each do |employee|
       payslip = Payslip.new(employee: employee, pay_period_start_date: @pay_period_start_date, pay_period_end_date: @pay_period_end_date )
       if payslip.errors.any?
         @errors = payslip.errors
       else
         @payslips << payslip
       end
     end
     @errors.empty?
  end

  def set_form_params
    @employees_for_select ||= Employee.all
  end

  def set_params
    @employees  = Employee.find(payslip_params[:employee_id])     if payslip_params[:employee_id]
    @pay_period_start_date = payslip_params[:payslip_start_date]  if payslip_params[:payslip_start_date]
    @pay_period_end_date   = payslip_params[:payslip_end_date]    if payslip_params[:payslip_end_date]
    @params_for_csv = {employee_id: @employees.map(&:id), payslip_end_date: @pay_period_end_date, payslip_start_date: @pay_period_start_date}
  end

  def payslip_params
    params[:payslips]
  end

end

app/views/payslips/_list.html.haml
%table.table

  %thead
    %th Name
    %th Pay Period
    %th.text-right Gross Income
    %th.text-right Income Tax
    %th.text-right Net Income
    %th.text-right Super

  %tbody
    - @payslips.each do |ps|
      %tr
        %td=ps.name
        %td=ps.pay_period
        %td.text-right=dollar(ps.gross_income)
        %td.text-right=dollar(ps.income_tax)
        %td.text-right=dollar(ps.net_income)
        %td.text-right=dollar(ps.super_amount)

.well
  Download:
  =link_to 'csv', payslips_export_csv_path(payslips: @params_for_csv, format: :csv)

app/views/payslips/index.html.haml
%h3 Create Payslips

=form_for :payslips, url: payslips_multiple_path,  method: :post, remote: :true, html: {class: 'form-horizontal'} do |f|
  .form-group
    =f.label :employee_id, 'Select employees:', class: 'control-label col-sm-2'
    .col-xs-10
      =f.select :employee_id, options_from_collection_for_select(@employees_for_select, :id, :full_name), {include_blank: false, include_hidden: false}, multiple: true, size: 5, class: 'form-control', required: true
  .form-group
    =f.label :payslip_start_date, 'Start Date:', class: 'control-label col-sm-2'
    .col-xs-10.col-sm-3.col-md-3
      =f.date_field :payslip_start_date, class: 'form-control input-medium', required: true
  .form-group
    =f.label :payslip_end_date, 'End Date:', class: 'control-label col-sm-2'
    .col-xs-10.col-sm-3.col-md-3
      =f.date_field :payslip_end_date, class: 'form-control input-medium', required: true
  .form-group
    .col-xs-10.col-sm-offset-2.col-sm-3.col-md-offset-2.col-md-10
      =f.submit 'Generate Payslips', class: 'btn btn-success'

#payslips_list

app/views/payslips/show_multiple.csv.erb
name,pay_period,gross_income,income_tax,net_income,super
<%= CSV.generate do |csv|
  @payslips.each do |ps|
    csv << [ps.name,
            ps.pay_period,
            ps.gross_income,
            ps.income_tax,
            ps.net_income,
            ps.super_amount
            ]
  end
end.html_safe %>

app/views/payslips/show_multiple.js.erb
$('#payslips_list').html("<%=escape_javascript(render 'payslips/list')%>");

app/views/payslips/show_multiple_errors.js.erb
window.location.replace("<%="#{payslips_url}"%>");