config/routes.rb
Rails.application.routes.draw do
  resources :employees do
    post :import, on: :collection
  end
  root "home#index"
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :first_name,    presence: true
  validates :last_name,     presence: true
  validates :annual_salary, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :super_rate,    presence: true, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0}

  before_validation :convert_from_pct_to_dec

  def full_name
    "#{self.last_name}, #{self.first_name}"
  end

  def self.import(file)
    everything_was_right = true
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end rescue everything_was_right = false
    everything_was_right
  end

  private

  def convert_from_pct_to_dec
    self.super_rate = self.super_rate.to_f/100 if percentage?
  end

  def percentage?
    (self.super_rate.to_s.include?('%')) or (self.super_rate.to_f > 1.0)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  add_crumb('Employees') {|instance| instance.send :employees_path }
  add_crumb('New Employee', only: ['new', 'create']) {|instance| instance.send :new_employee_path }
  add_crumb('Edit Employee', only: ['edit']) {|instance| instance.send :edit_employee_path }

  def index
    @employees = Employee.order(:id)
  end

  def new
    @employee = Employee.new
  end

  def import
    if Employee.import(import_params)
      flash[:notice] = 'Employees are imported without problem.'
    else
      flash[:error] = 'Import was not perfect. Please check your csv file.'
    end
    redirect_to employees_url
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'Employee was successfully created.' }
      else
        flash.now[:error] = @employee.errors.full_messages
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
      else
        flash.now[:error] = @employee.errors.full_messages
        format.html { render :edit }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      flash[:error] = "Employee was deleted from the database."
      format.html { redirect_to employees_url }
    end
  end

  private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params[:employee].permit(:first_name, :last_name, :annual_salary, :super_rate)
    end

    def import_params
      params[:file]
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.haml
=form_for @employee, html: {class: 'form-horizontal'} do |f|
  .form-group
    =f.label :first_name, 'First Name: ', class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :first_name, class: 'form-control', autofocus: true, placeholder: 'First Name'
  .form-group
    =f.label :last_name, 'Last Name: ', class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :last_name, class: 'form-control', placeholder: 'Last Name'
  .form-group
    =f.label :annual_salary, 'Annual Salary ($):', class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :annual_salary, class: 'form-control', placeholder: 'ex. 85000'
  .form-group
    =f.label :super_rate, 'Super Rate: ', class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :super_rate, class: 'form-control', placeholder: 'ex. 9% or 0.09'
  .form-group
    .col-sm-offset-2.col-sm-10
      =button_tag 'Reset', type: :reset, class: 'btn'
      =f.submit (@employee.new_record? ? 'Create' : 'Update'), class: 'btn btn-success'
.well.well-small
  =link_to '<< Back to the list', employees_path

app/views/employees/_list.html.haml
%table.table

  %thead
    %th ID
    %th First Name
    %th Last Name
    %th.text-right Annual Salary
    %th.text-right Super Rate
    %th.text-right Actions

  %tbody
    - @employees.each do |employee|
      %tr
        %td=employee.id
        %td=employee.first_name
        %td=employee.last_name
        %td.text-right=dollar(employee.annual_salary)
        %td.text-right="#{'%.2f'%(employee.super_rate*100)}%"
        %td.text-right
          =link_to 'Edit', edit_employee_path(employee), class: 'btn btn-success'
          =link_to 'X', employee_path(employee), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

app/views/employees/edit.html.haml
= render 'form'

app/views/employees/index.html.haml
=link_to 'Add Employee', new_employee_path, class: 'btn btn-primary pull-right'

%h3 List of Employees

- if @employees.empty?
  .well
    %p No employee in the database. You can choose the following options to upload employees:
    %ol
      %li Create record with form manually. Click to Add Employee button.
      %li Run seed import. (rake db:seed)
      %li Import employees from csv file.

- else

  =render 'list'

%h3 Import Employees

.well
  =form_tag import_employees_path, multipart: true do
    %p Import Employees from a csv file.
    =file_field_tag :file, id: 'file-button'
    %p.help-block The header of csv file must be: first_name,last_name,annual_salary,super_rate
    =submit_tag 'Import', class: 'btn btn-warning'

app/views/employees/new.html.haml
= render 'form'