config/routes.rb
Rails.application.routes.draw do
  resources :employees do
    post :import, on: :collection
  end
  root "home#index"
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
end

app/views/layouts/_messages.html.haml
-flash.each do |name, msg|
  %div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
    %button.close{data: {dismiss: 'alert'}} ×
    - if msg.is_a?(String)
      =content_tag :div, msg, id: "flash_#{name}"
    - if msg.is_a?(Array)
      - msg.each do |m|
        =content_tag :div, m

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WorkPay Calculator
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.navbar-inverse
        .navbar-header
          %button.navbar-toggle{data: {toggle:'collapse', target:'#menubar'}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'PaySlip App', root_path, class: 'navbar-brand'
        #menubar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li=link_to 'Home', root_path, class: ('active' if controller_name == 'home')
            %li=link_to 'Employees', employees_path, class: ('active' if controller_name == 'employees')
            %li=link_to 'Payslips', payslips_path, class: ('active' if controller_name == 'payslips')

      - unless current_page?(root_url)
        %ol.breadcrumb
          =render_crumbs
      =render 'layouts/messages'

      = yield
      .footer
        - unless controller_name == 'home'
          %hr
        =link_to "Jampana Varma", "http://www.codevarma.com"
        |
        =link_to "LinkedIn", "http://www.linkedin.com/in/jampanavarma"
        |
        =link_to "Twitter", "http://twitter.com/jvssvarma"
        |
        =link_to "GitHub", "http://github.com/jvssvarma"


    - if controller_name == 'home'
      .image-holder